# Generated by Django 2.2.7 on 2019-11-25 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='search',
            new_name='search_content',
        ),
    ]
