# Generated by Django 2.2.7 on 2019-11-25 17:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20191125_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 17, 44, 42, 471826, tzinfo=utc)),
        ),
    ]
